// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pathfinder.Models;

namespace Pathfinder.Migrations
{
    [DbContext(typeof(MeshNodeContext))]
    [Migration("20210103222039_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresExtension("postgis")
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Pathfinder.Models.MeshNode", b =>
                {
                    b.Property<long>("WorldId")
                        .HasColumnType("bigint");

                    b.Property<string>("NodeId")
                        .HasColumnType("text");

                    b.Property<string>("BlockId")
                        .HasColumnType("text");

                    b.Property<Point>("Pos")
                        .HasColumnType("geometry (pointz)");

                    b.HasKey("WorldId", "NodeId");

                    b.HasIndex("Pos")
                        .HasMethod("SPGIST")
                        .HasOperators(new[] { "spgist_geometry_ops_3d" });

                    b.ToTable("MeshNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
